namespace Microsoft.Xbox.Services.Achievements
{
    enum AchievementMediaAssetType
    {
        Unknown,
        Icon,
        Art,
    };

    enum AchievementOrderBy
    {
        Default,
        TitleId,
        UnlockTime,
    };

    enum AchievementParticipationType
    {
        Unknown,
        Individual,
        Group,
    };

    enum AchievementProgressState
    {
        Unknown,
        Achieved,
        NotStarted,
        InProgress,
    };

    enum AchievementRewardType
    {
        Unknown,
        Gamerscore,
        InApp,
        Art,
    };

    enum AchievementType
    {
        Unknown,
        All,
        Persistent,
        Challenge,
    };

    [interface_name("__IAchievementPublicNonVirtuals", 82424441-5E17-32E3-AD51-8D1010C911B1)]
    runtimeclass Achievement
    {
        String Id { get; };
        String ServiceConfigurationId { get; };
        String Name { get; };
        Windows.Foundation.Collections.IVectorView<AchievementTitleAssociation> TitleAssociations { get; };
        AchievementProgressState ProgressState { get; };
        AchievementProgression Progression { get; };
        Windows.Foundation.Collections.IVectorView<AchievementMediaAsset> MediaAssets { get; };
        Windows.Foundation.Collections.IVectorView<String> PlatformsAvailableOn { get; };
        Boolean IsSecret { get; };
        String UnlockedDescription { get; };
        String LockedDescription { get; };
        String ProductId { get; };
        AchievementType AchievementType { get; };
        AchievementParticipationType ParticipationType { get; };
        AchievementTimeWindow Available { get; };
        Windows.Foundation.Collections.IVectorView<AchievementReward> Rewards { get; };
        Windows.Foundation.TimeSpan EstimatedUnlockTime { get; };
        String DeepLink { get; };
        Boolean IsRevoked { get; };
    }

    [interface_name("__IAchievementMediaAssetPublicNonVirtuals", 3CE72950-7EF1-369E-A510-BF4D26DCD129)]
    runtimeclass AchievementMediaAsset
    {
        String Name { get; };
        AchievementMediaAssetType MediaAssetType { get; };
        String Url { get; };
    }

    [interface_name("__IAchievementProgressionPublicNonVirtuals", 63E20CA3-78E1-3587-A3DB-F1E6EC6FA1E9)]
    runtimeclass AchievementProgression
    {
        Windows.Foundation.Collections.IVectorView<AchievementRequirement> Requirements { get; };
        Windows.Foundation.DateTime TimeUnlocked { get; };
    }

    [interface_name("__IAchievementRequirementPublicNonVirtuals", 69D62348-8641-36E6-B097-3EB2C9F17E91)]
    runtimeclass AchievementRequirement
    {
        String Id { get; };
        String CurrentProgressValue { get; };
        String TargetProgressValue { get; };
    }

    [interface_name("__IAchievementRewardPublicNonVirtuals", 634388A7-1CA8-3CE9-9711-16CE27DC3F24)]
    runtimeclass AchievementReward
    {
        String Name { get; };
        String Description { get; };
        String Data { get; };
        AchievementRewardType RewardType { get; };
        Windows.Foundation.PropertyType ValuePropertyType { get; };
        AchievementMediaAsset MediaAsset { get; };
    }

    [interface_name("__IAchievementServicePublicNonVirtuals", 09B122FA-0CDF-3F97-912C-0D37F444231D)]
    runtimeclass AchievementService
    {
        [method_name("UpdateAchievementAsync2")]
        Windows.Foundation.IAsyncAction UpdateAchievementAsync(String xboxUserId, String achievementId, UInt32 percentComplete);
        [method_name("UpdateAchievementAsync1")]
        Windows.Foundation.IAsyncAction UpdateAchievementAsync(String xboxUserId, UInt32 titleId, String serviceConfigurationId, String achievementId, UInt32 percentComplete);
        Windows.Foundation.IAsyncOperation<AchievementsResult> GetAchievementsForTitleIdAsync(String xboxUserId, UInt32 titleId, AchievementType type, Boolean unlockedOnly, AchievementOrderBy orderBy, UInt32 skipItems, UInt32 maxItems);
        Windows.Foundation.IAsyncOperation<Achievement> GetAchievementAsync(String xboxUserId, String serviceConfigurationId, String achievementId);
    }

    [interface_name("__IAchievementsResultPublicNonVirtuals", A5B75CB8-804B-3C73-A78A-701B7C027C04)]
    runtimeclass AchievementsResult
    {
        Windows.Foundation.Collections.IVectorView<Achievement> Items { get; };
        Windows.Foundation.IAsyncOperation<AchievementsResult> GetNextAsync(UInt32 maxItems);
        Boolean HasNext { get; };
    }

    [interface_name("__IAchievementTimeWindowPublicNonVirtuals", 400B6A0C-CCB5-3385-A746-76AB089A524E)]
    runtimeclass AchievementTimeWindow
    {
        Windows.Foundation.DateTime StartDate { get; };
        Windows.Foundation.DateTime EndDate { get; };
    }

    [interface_name("__IAchievementTitleAssociationPublicNonVirtuals", 59AE7969-946B-330F-A6DC-CAE3A531DAF8)]
    runtimeclass AchievementTitleAssociation
    {
        String Name { get; };
        UInt32 TitleId { get; };
    }
}