import "Microsoft.Xbox.Services.Multiplayer.idl";
namespace Microsoft.Xbox.Services.Matchmaking
{
    enum PreserveSessionMode
    {
        Unknown,
        Always,
        Never,
    };

    enum TicketStatus
    {
        Unknown,
        Expired,
        Searching,
        Found,
        Canceled,
    };

    [interface_name("__ICreateMatchTicketResponsePublicNonVirtuals", C8A4E252-CC3A-3C0F-92F2-127CEF0CF7AC)]
    runtimeclass CreateMatchTicketResponse
    {
        String MatchTicketId { get; };
        Windows.Foundation.TimeSpan EstimatedWaitTime { get; };
    }

    [interface_name("__IHopperStatisticsResponsePublicNonVirtuals", AC6AB0AE-BFCC-3C82-80D4-B64E4B5F9BBE)]
    runtimeclass HopperStatisticsResponse
    {
        String HopperName { get; };
        Windows.Foundation.TimeSpan EstimatedWaitTime { get; };
        UInt32 PlayersWaitingToMatch { get; };
    }

    [interface_name("__IMatchmakingServicePublicNonVirtuals", 734B7637-E6F0-3AFA-AD16-AF54959436F7)]
    runtimeclass MatchmakingService
    {
        Windows.Foundation.IAsyncOperation<CreateMatchTicketResponse> CreateMatchTicketAsync(
            Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference ticketSessionReference,
            String matchmakingServiceConfigurationId,
            String hopperName,
            Windows.Foundation.TimeSpan ticketTimeout,
            PreserveSessionMode preserveSession,
            String ticketAttributesJson);
        Windows.Foundation.IAsyncAction DeleteMatchTicketAsync(
            String serviceConfigurationId,
            String hopperName,
            String ticketId);
        Windows.Foundation.IAsyncOperation<MatchTicketDetailsResponse> GetMatchTicketDetailsAsync(
            String serviceConfigurationId,
            String hopperName,
            String ticketId);
        Windows.Foundation.IAsyncOperation<HopperStatisticsResponse> GetHopperStatisticsAsync(
            String serviceConfigurationId,
            String hopperName);
    }

    [interface_name("__IMatchTicketDetailsResponsePublicNonVirtuals", 8A2649C9-BE8F-3FC5-B78D-802B1833DD0B)]
    runtimeclass MatchTicketDetailsResponse
    {
        TicketStatus MatchStatus { get; };
        Windows.Foundation.TimeSpan EstimatedWaitTime { get; };
        PreserveSessionMode PreserveSession { get; };
        Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference TicketSession { get; };
        Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference TargetSession { get; };
        String TicketAttributes { get; };
    }
}