import "Microsoft.Xbox.Services.idl";
namespace Microsoft.Xbox.Services.Multiplayer
{
    enum MatchmakingStatus
    {
        Unknown,
        None,
        Searching,
        Expired,
        Found,
        Canceled,
    };

    enum MultiplayerInitializationStage
    {
        Unknown,
        None,
        Joining,
        Measuring,
        Evaluating,
        Failed,
    };

    enum MultiplayerMeasurementFailure
    {
        Unknown,
        None,
        Timeout,
        Latency,
        BandwidthUp,
        BandwidthDown,
        Group,
        Network,
        Episode,
    };

    enum MultiplayerSessionChangeTypes
    {
        None = 0,
        Everything = 1,
        HostDeviceTokenChange = 2,
        InitializationStateChange = 4,
        MatchmakingStatusChange = 8,
        MemberListChange = 16,
        MemberStatusChange = 32,
        SessionJoinabilityChange = 64,
        CustomPropertyChange = 128,
        MemberCustomPropertyChange = 256,
        TournamentPropertyChange = 512,
        ArbitrationPropertyChange = 1024,
    };

    enum MultiplayerSessionMemberStatus
    {
        Reserved,
        Inactive,
        Ready,
        Active,
    };

    enum MultiplayerSessionRestriction
    {
        Unknown,
        None,
        Local,
        Followed,
    };

    enum MultiplayerSessionStatus
    {
        Unknown,
        Active,
        Inactive,
        Reserved,
    };

    enum MultiplayerSessionVisibility
    {
        Unknown,
        Any,
        Private,
        Visible,
        Full,
        Open,
    };

    enum MultiplayerSessionWriteMode
    {
        CreateNew,
        UpdateOrCreateNew,
        UpdateExisting,
        SynchronizedUpdate,
    };

    enum MultiplayMetrics
    {
        Unknown,
        BandwidthUp,
        BandwidthDown,
        Bandwidth,
        Latency,
    };

    enum MutableRoleSetting
    {
        Max,
        Target,
    };

    enum NetworkAddressTranslationSetting
    {
        Unknown,
        Open,
        Moderate,
        Strict,
    };

    enum WriteSessionStatus
    {
        Unknown,
        AccessDenied,
        Created,
        Conflict,
        HandleNotFound,
        OutOfSync,
        SessionDeleted,
        Updated,
    };

    [interface_name("__IMultiplayerActivityDetailsPublicNonVirtuals", 53305C6D-739B-376B-80E8-3326830AF6D8)]
    runtimeclass MultiplayerActivityDetails
    {
        Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference SessionReference { get; };
        String HandleId { get; };
        UInt32 TitleId { get; };
        MultiplayerSessionVisibility Visibility { get; };
        MultiplayerSessionRestriction JoinRestriction { get; };
        Boolean Closed { get; };
        String OwnerXboxUserId { get; };
        UInt32 MaxMembersCount { get; };
        UInt32 MembersCount { get; };
        String CustomSessionPropertiesJson { get; };
    }

    [interface_name("__IMultiplayerGetSessionsRequestFactory", A6CC2F15-DD97-398D-9697-5714A1237154)]
    runtimeclass MultiplayerGetSessionsRequest
    {
        MultiplayerGetSessionsRequest();
        [constructor_name("__IMultiplayerGetSessionsRequestFactory", 6171E340-4846-3DFA-9E61-3F8B89F91AAA)]
        {
            MultiplayerGetSessionsRequest(String serviceConfigurationId, UInt32 maxItems);
        }
        String ServiceConfigurationId { get; };
        UInt32 MaxItems { get; };
        Boolean IncludePrivateSessions { get; set; };
        Boolean IncludeReservations { get; set; };
        Boolean IncludeInactiveSessions { get; set; };
        String XboxUserIdFilter { get; set; };
        Windows.Foundation.Collections.IVectorView<String> XboxUserIdsFilter { get; set; };
        String KeywordFilter { get; set; };
        String SessionTemplateNameFilter { get; set; };
        MultiplayerSessionVisibility VisibilityFilter { get; set; };
        UInt32 ContractVersionFilter { get; set; };
    }

    [interface_name("__IMultiplayerManagedInitializationPublicNonVirtuals", 3529F4B5-C8C3-3450-8C0B-ED9CCC7D3B43)]
    runtimeclass MultiplayerManagedInitialization
    {
        Boolean ManagedInitializationSet { get; };
        Windows.Foundation.TimeSpan JoinTimeout { get; };
        Windows.Foundation.TimeSpan MeasurementTimeout { get; };
        Windows.Foundation.TimeSpan EvaluationTimeout { get; };
        Boolean AutoEvaluate { get; };
        UInt32 MembersNeededToStart { get; };
    }

    [interface_name("__IMultiplayerMemberInitializationPublicNonVirtuals", EA083398-9FCE-3AE2-9675-58F864582BB3)]
    runtimeclass MultiplayerMemberInitialization
    {
        Boolean MemberInitializationSet { get; };
        Windows.Foundation.TimeSpan JoinTimeout { get; };
        Windows.Foundation.TimeSpan MeasurementTimeout { get; };
        Windows.Foundation.TimeSpan EvaluationTimeout { get; };
        Boolean ExternalEvaluation { get; };
        UInt32 MembersNeededToStart { get; };
    }

    [interface_name("__IMultiplayerPeerToHostRequirementsPublicNonVirtuals", D65923C4-377A-3D2A-B386-BBCC51DF563B)]
    runtimeclass MultiplayerPeerToHostRequirements
    {
        Windows.Foundation.TimeSpan LatencyMaximum { get; };
        UInt64 BandwidthDownMinimumInKilobitsPerSecond { get; };
        UInt64 BandwidthUpMinimumInKilobitsPerSecond { get; };
        MultiplayMetrics HostSelectionMetric { get; };
    }

    [interface_name("__IMultiplayerPeerToPeerRequirementsPublicNonVirtuals", 542B9A2F-2DBC-3531-AEA5-70A65A632798)]
    runtimeclass MultiplayerPeerToPeerRequirements
    {
        Windows.Foundation.TimeSpan LatencyMaximum { get; };
        UInt64 BandwidthMinimumInKilobitsPerSecond { get; };
    }

    [interface_name("__IMultiplayerQualityOfServiceMeasurementsPublicNonVirtuals", 59AE7969-946B-330F-A6DC-CAE3A531DAF8)]
    runtimeclass MultiplayerQualityOfServiceMeasurements
    {
        MultiplayerQualityOfServiceMeasurements();
        [constructor_name("__IMultiplayerQualityOfServiceMeasurementsFactory", 31F504A3-E299-30BB-8192-1499302DC716)]
        {
            MultiplayerQualityOfServiceMeasurements(String memberDeviceToken, Windows.Foundation.TimeSpan latency, UInt64 bandwidthDownInKilobitsPerSecond, 
                UInt64 bandwidthUpInKilobitsPerSecond, String customJson);
        }
        String MemberDeviceToken { get; };
        Windows.Foundation.TimeSpan Latency { get; };
        UInt64 BandwidthDownInKilobitsPerSecond { get; };
        UInt64 BandwidthUpInKilobitsPerSecond { get; };
        String CustomJson { get; };
    }

    [interface_name("__IMultiplayerQuerySearchHandleRequestPublicNonVirtuals", 784DF025-7F33-3920-AE8C-E4FC5DD22613)]
    runtimeclass MultiplayerQuerySearchHandleRequest
    {
        MultiplayerQuerySearchHandleRequest();
        [constructor_name("__IMultiplayerQuerySearchHandleRequestFactory", 60FA4058-9047-3060-9259-6F2F1F2011EE)]
        {
            MultiplayerQuerySearchHandleRequest(String serviceConfigurationId, String sessionTemplateName);
        }
        String ServiceConfigurationId { get; };
        String SessionTemplateName { get; };
        String OrderBy { get; set; };
        Boolean OrderAscending { get; set; };
        String SearchFilter { get; set; };
        String SocialGroup { get; set; };
    }

    [interface_name("__IMultiplayerRoleInfoPublicNonVirtuals", 6717C834-28D0-3B29-896C-900C92B3ADEA)]
    runtimeclass MultiplayerRoleInfo
    {
        Windows.Foundation.Collections.IVectorView<String> MemberXboxUserIds { get; };
        UInt32 MembersCount { get; };
        UInt32 TargetCount { get; set; };
        UInt32 MaxMembersCount { get; set; };
    }

    [interface_name("__IMultiplayerRoleTypePublicNonVirtuals", 3D91948B-802B-3B76-B2CA-5BE46AC3F286)]
    runtimeclass MultiplayerRoleType
    {
        Boolean OwnerManaged { get; };
        Windows.Foundation.Collections.IVectorView<MutableRoleSetting> MutableRoleSettings { get; };
        Windows.Foundation.Collections.IMap<String, MultiplayerRoleInfo> Roles { get; set; };
    }

    [interface_name("__IMultiplayerSearchHandleDetailsPublicNonVirtuals", B5309ABB-C608-3FD9-B251-831155FB31B3)]
    runtimeclass MultiplayerSearchHandleDetails
    {
        MultiplayerSessionReference SessionReference { get; };
        String HandleId { get; };
        Windows.Foundation.Collections.IVectorView<String> SessionOwnerXboxUserIds { get; };
        Windows.Foundation.Collections.IVectorView<String> Tags { get; };
        Windows.Foundation.Collections.IMap<String, Double> NumbersMetadata { get; };
        Windows.Foundation.Collections.IMap<String, String> StringsMetadata { get; };
        Windows.Foundation.Collections.IMap<String, MultiplayerRoleType> RoleTypes { get; };
        MultiplayerSessionVisibility Visibility { get; };
        MultiplayerSessionRestriction JoinRestriction { get; };
        Boolean Closed { get; };
        UInt32 MaxMembersCount { get; };
        UInt32 MembersCount { get; };
        Windows.Foundation.DateTime HandleCreationTime { get; };
        String CustomSessionPropertiesJson { get; };
    }

    [interface_name("__IMultiplayerSearchHandleRequestPublicNonVirtuals", D19FF83D-3A08-304E-80E6-7783D4BDCDC8)]
    runtimeclass MultiplayerSearchHandleRequest
    {
        MultiplayerSearchHandleRequest();
        [constructor_name("__IMultiplayerSearchHandleRequestFactory", 26BA91FF-EFB0-31BA-A704-333B9B8C31E5)]
        {
            MultiplayerSearchHandleRequest(MultiplayerSessionReference sessionReference);
        }
        MultiplayerSessionReference SessionReference { get; };
        Windows.Foundation.Collections.IVectorView<String> Tags { get; set; };
        Windows.Foundation.Collections.IMap<String, Double> NumbersMetadata { get; set; };
        Windows.Foundation.Collections.IMap<String, String> StringsMetadata { get; set; };
    }

    [interface_name("__IMultiplayerServicePublicNonVirtuals", 4B294BF8-4CF7-363F-9415-D35C8FC3F27C)]
    runtimeclass MultiplayerService
    {
        [interface_name("__IMultiplayerServiceProtectedNonVirtuals", 046E9A52-2DC0-3789-B90B-054040CD9CC9)]
        {
        }
        event Windows.Foundation.EventHandler<MultiplayerSessionChangeEventArgs> MultiplayerSessionChanged;
        event Windows.Foundation.EventHandler<MultiplayerSubscriptionLostEventArgs> MultiplayerSubscriptionLost;
        Windows.Foundation.IAsyncOperation<MultiplayerSession> WriteSessionAsync(
            MultiplayerSession multiplayerSession,
            MultiplayerSessionWriteMode multiplayerSessionWriteMode);
        Windows.Foundation.IAsyncOperation<WriteSessionResult> TryWriteSessionAsync(
            MultiplayerSession multiplayerSession,
            MultiplayerSessionWriteMode multiplayerSessionWriteMode);
        Windows.Foundation.IAsyncOperation<MultiplayerSession> WriteSessionByHandleAsync(
            MultiplayerSession multiplayerSession,
            MultiplayerSessionWriteMode multiplayerSessionWriteMode,
            String handleId);
        Windows.Foundation.IAsyncOperation<WriteSessionResult> TryWriteSessionByHandleAsync(
            MultiplayerSession multiplayerSession,
            MultiplayerSessionWriteMode multiplayerSessionWriteMode,
            String handleId);
        Windows.Foundation.IAsyncOperation<MultiplayerSession> GetCurrentSessionAsync(
            MultiplayerSessionReference sessionReference);
        Windows.Foundation.IAsyncOperation<MultiplayerSession> GetCurrentSessionByHandleAsync(String handleId);
        [method_name("GetSessionsAsync2")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerSessionStates> > GetSessionsAsync(MultiplayerGetSessionsRequest getSessionsRequest);
        [method_name("GetSessionsAsync1")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerSessionStates> > GetSessionsAsync(
            String serviceConfigurationId,
            String sessionTemplateNameFilter,
            String xboxUserIdFilter,
            String keywordFilter,
            MultiplayerSessionVisibility visibilityFilter,
            UInt32 contractVersionFilter,
            Boolean includePrivateSessions,
            Boolean includeReservations,
            Boolean includeInactiveSessions,
            UInt32 maxItems);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerSessionStates> > GetSessionsForUsersFilterAsync(
            String serviceConfigurationId,
            String sessionTemplateNameFilter,
            Windows.Foundation.Collections.IVectorView<String> xboxUserIdsFilter,
            String keywordFilter,
            MultiplayerSessionVisibility visibilityFilter,
            UInt32 contractVersionFilter,
            Boolean includePrivateSessions,
            Boolean includeReservations,
            Boolean includeInactiveSessions,
            UInt32 maxItems);
        IAsyncAction SetActivityAsync(MultiplayerSessionReference sessionReference);
        Windows.Foundation.IAsyncOperation<String> SetTransferHandleAsync(
            MultiplayerSessionReference targetSessionReference,
            MultiplayerSessionReference originSessionReference);
        IAsyncAction SetSearchHandleAsync(MultiplayerSearchHandleRequest searchHandleRequest);
        IAsyncAction ClearActivityAsync(String serviceConfigurationId);
        IAsyncAction ClearSearchHandleAsync(String handleId);
        [method_name("SendInvitesAsync2")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<String> > SendInvitesAsync(
            MultiplayerSessionReference sessionReference,
            Windows.Foundation.Collections.IVectorView<String> xboxUserIds,
            UInt32 titleId);
        [method_name("SendInvitesAsync1")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<String> > SendInvitesAsync(
            MultiplayerSessionReference sessionReference,
            Windows.Foundation.Collections.IVectorView<String> xboxUserIds,
            UInt32 titleId,
            String contextStringId,
            String activationContext);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerActivityDetails> > GetActivitiesForSocialGroupAsync(
            String serviceConfigurationId,
            String socialGroupOwnerXboxUserId,
            String socialGroup);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerActivityDetails> > GetActivitiesForUsersAsync(
            String serviceConfigurationId,
            Windows.Foundation.Collections.IVectorView<String> xboxUserIds);
        [method_name("GetSearchHandlesAsync2")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerSearchHandleDetails> > GetSearchHandlesAsync(
            String serviceConfigurationId,
            String sessionTemplateName,
            String orderBy,
            Boolean orderAscending,
            String searchFilter);
        [method_name("GetSearchHandlesAsync1")]
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<MultiplayerSearchHandleDetails> > GetSearchHandlesAsync(
            MultiplayerQuerySearchHandleRequest searchHandleRequest);
        void EnableMultiplayerSubscriptions();
        void DisableMultiplayerSubscriptions();
        Boolean MultiplayerSubscriptionsEnabled { get; };
    }

    [interface_name("__IMultiplayerSessionPublicNonVirtuals", 8BCE98DE-EF37-3120-BB37-0DEA877A8AFE)]
    [static_name("__IMultiplayerSessionStatics", 8821DA91-7CAB-3E33-A26B-07F139C4BBC8)]
    runtimeclass MultiplayerSession
    {
        MultiplayerSession();
        [constructor_name("__IMultiplayerSessionFactory", 8A63BF8F-E772-384F-A87F-82CC01EAF837)]
        {
            MultiplayerSession(Microsoft.Xbox.Services.XboxLiveContext xboxLiveContext);
            MultiplayerSession(Microsoft.Xbox.Services.XboxLiveContext xboxLiveContext,
                MultiplayerSessionReference multiplayerSessionReference,
                UInt32 maxMembersInSession,
                MultiplayerSessionVisibility multiplayerSessionVisibility,
                Windows.Foundation.Collections.IVectorView<String> initiatorXboxUserIds,
                String sessionCustomConstantsJson);
            MultiplayerSession(Microsoft.Xbox.Services.XboxLiveContext xboxLiveContext, MultiplayerSessionReference multiplayerSessionReference);
        }
        static MultiplayerSessionChangeTypes CompareMultiplayerSessions(
            MultiplayerSession currentSession,
            MultiplayerSession oldSession);
        static WriteSessionStatus ConvertHttpStatusToWriteSessionStatus(Int32 httpStatusCode);
        String MultiplayerCorrelationId { get; };
        String SearchHandleId { get; };
        TournamentArbitrationStatus ArbitrationStatus { get; };
        Windows.Foundation.DateTime StartTime { get; };
        Windows.Foundation.DateTime DateOfNextTimer { get; };
        Windows.Foundation.DateTime DateOfSession { get; };
        MultiplayerInitializationStage InitializationStage { get; };
        Windows.Foundation.DateTime InitializingStageStartTime { get; };
        UInt32 InitializingEpisode { get; };
        WriteSessionStatus WriteStatus { get; };
        Windows.Foundation.Collections.IVectorView<String> HostCandidates { get; };
        MultiplayerSessionReference SessionReference { get; };
        MultiplayerSessionConstants SessionConstants { get; };
        MultiplayerSessionProperties SessionProperties { get; };
        MultiplayerSessionRoleTypes SessionRoleTypes { get; };
        Windows.Foundation.Collections.IVectorView<MultiplayerSessionMember> Members { get; };
        MultiplayerSessionMatchmakingServer MatchmakingServer { get; };
        MultiplayerSessionTournamentsServer TournamentsServer { get; };
        MultiplayerSessionArbitrationServer ArbitrationServer { get; };
        UInt32 MembersAccepted { get; };
        String ServersJson { get; set; };
        String ETag { get; };
        MultiplayerSessionChangeTypes SubscribedChangeTypes { get; };
        MultiplayerSessionMember CurrentUser { get; };
        String Branch { get; };
        UInt64 ChangeNumber { get; };
        [method_name("AddMemberReservation2")]
        void AddMemberReservation(String xboxUserId, String memberCustomConstantsJson);
        [method_name("AddMemberReservation1")]
        void AddMemberReservation(
            String xboxUserId,
            String memberCustomConstantsJson,
            Boolean initializeRequested);
        [method_name("Join4")]
        MultiplayerSessionMember Join();
        [method_name("Join3")]
        MultiplayerSessionMember Join(String memberCustomConstantsJson);
        [method_name("Join2")]
        MultiplayerSessionMember Join(String memberCustomConstantsJson, Boolean initializeRequested);
        [method_name("Join1")]
        MultiplayerSessionMember Join(
            String memberCustomConstantsJson,
            Boolean initializeRequested,
            Boolean joinWithActiveStatus);
        void SetVisibility(MultiplayerSessionVisibility visibility);
        void SetMaxMembersInSession(UInt32 maxMembersInSession);
        void SetMutableRoleSettings(
            Windows.Foundation.Collections.IMap<String, MultiplayerRoleType> roleTypes);
        void SetTimeouts(
            Windows.Foundation.TimeSpan memberReservedTimeout,
            Windows.Foundation.TimeSpan memberInactiveTimeout,
            Windows.Foundation.TimeSpan memberReadyTimeout,
            Windows.Foundation.TimeSpan sessionEmptyTimeout);
        void SetArbitrationTimeouts(TimeSpan arbitrationTimeout, Windows.Foundation.TimeSpan forfeitTimeout);
        void SetQualityOfServiceConnectivityMetrics(
            Boolean enableLatencyMetric,
            Boolean enableBandwidthDownMetric,
            Boolean enableBandwidthUpMetric,
            Boolean enableCustomMetric);
        void SetManagedInitialization(
            Windows.Foundation.TimeSpan joinTimeout,
            Windows.Foundation.TimeSpan measurementTimeout,
            Windows.Foundation.TimeSpan evaluationTimeout,
            Boolean autoEvalute,
            UInt32 membersNeededToStart);
        void SetMemberInitialization(
            Windows.Foundation.TimeSpan joinTimeout,
            Windows.Foundation.TimeSpan measurementTimeout,
            Windows.Foundation.TimeSpan evaluationTimeout,
            Boolean autoEvalute,
            UInt32 membersNeededToStart);
        void SetPeerToPeerRequirements(TimeSpan latencyMaximum, UInt32 bandwidthMinimumInKilobitsPerSecond);
        void SetPeerToHostRequirements(
            Windows.Foundation.TimeSpan latencyMaximum,
            UInt32 bandwidthDownMinimumInKilobitsPerSecond,
            UInt32 bandwidthUpMinimumInKilobitsPerSecond,
            MultiplayMetrics hostSelectionMetric);
        void SetMeasurementServerAddresses(
            Windows.Foundation.Collections.IVectorView<QualityOfServiceServer> measurementServerAddresses);
        void SetCloudComputePackageJson(String sessionCloudComputePackageConstantsJson);
        void SetSessionCapabilities(MultiplayerSessionCapabilities capabilities);
        void SetInitializationStatus(Boolean initializationSucceeded);
        void SetHostDeviceToken(String hostDeviceToken);
        void SetMatchmakingServerConnectionPath(String serverConnectionPath);
        void SetClosed(Boolean closed);
        void SetLocked(Boolean locked);
        void SetAllocateCloudCompute(Boolean allocateCloudCompute);
        void SetMatchmakingResubmit(Boolean matchResubmit);
        void SetServerConnectionStringCandidates(
            Windows.Foundation.Collections.IVectorView<String> serverConnectionStringCandidates);
        void SetSessionChangeSubscription(MultiplayerSessionChangeTypes changeTypes);
        void Leave();
        void SetCurrentUserStatus(MultiplayerSessionMemberStatus status);
        void SetCurrentUserSecureDeviceAddressBase64(String value);
        void SetCurrentUserRoleInfo(Windows.Foundation.Collections.IMap<String, String> roles);
        void SetCurrentUserMembersInGroup(
            Windows.Foundation.Collections.IVectorView<MultiplayerSessionMember> membersInGroup);
        void SetCurrentUserQualityOfServiceMeasurements(
            Windows.Foundation.Collections.IVectorView<MultiplayerQualityOfServiceMeasurements> measurements);
        void SetCurrentUserQualityOfServiceServerMeasurementsJson(String valueJson);
        void SetCurrentUserArbitrationResults(
            Windows.Foundation.Collections.IMap<String, TournamentTeamResult> results);
        void SetCurrentUserMemberCustomPropertyJson(String name, String valueJson);
        void DeleteCurrentUserMemberCustomPropertyJson(String name);
        void SetMatchmakingTargetSessionConstantsJson(String matchmakingTargetSessionConstants);
        void SetSessionCustomPropertyJson(String name, String valueJson);
        void DeleteSessionCustomPropertyJson(String name);
        void _Init(
            Microsoft.Xbox.Services.XboxLiveContext xboxLiveContext,
            MultiplayerSessionReference multiplayerSessionReference,
            UInt32 maxMembersInSession,
            MultiplayerSessionVisibility multiplayerSessionVisibility,
            Windows.Foundation.Collections.IVectorView<String> initiatorXboxUserIds,
            String sessionCustomConstantsJson);
    }

    [interface_name("__IMultiplayerSessionArbitrationServerPublicNonVirtuals", 13D13CAA-6B68-341D-9676-B4F26CB5EB50)]
    runtimeclass MultiplayerSessionArbitrationServer
    {
        Windows.Foundation.DateTime ArbitrationStartTime { get; };
        TournamentArbitrationState ResultState { get; };
        TournamentGameResultSource ResultSource { get; };
        UInt32 ResultConfidenceLevel { get; };
        Windows.Foundation.Collections.IMap<String, TournamentTeamResult> Results { get; };
    }

    [interface_name("__IMultiplayerSessionCapabilitiesPublicNonVirtuals", 65631F01-B22C-30C4-BCCC-6C22E25EF67B)]
    runtimeclass MultiplayerSessionCapabilities
    {
        Boolean Connectivity { get; set; };
        Boolean SuppressPresenceActivityCheck { get; set; };
        Boolean Gameplay { get; set; };
        Boolean Large { get; set; };
        Boolean ConnectionRequiredForActiveMembers { get; set; };
        Boolean UserAuthorizationStyle { get; set; };
        Boolean Crossplay { get; set; };
        Boolean Team { get; set; };
        Boolean Arbitration { get; set; };
        Boolean Searchable { get; set; };
        Boolean HasOwners { get; set; };
    }

    [interface_name("__IMultiplayerSessionChangeEventArgsPublicNonVirtuals", 57CCF7F2-CA61-3015-9D79-FEBF8E9928FE)]
    runtimeclass MultiplayerSessionChangeEventArgs
    {
        MultiplayerSessionReference SessionReference { get; };
        String Branch { get; };
        UInt64 ChangeNumber { get; };
    }

    [interface_name("__IMultiplayerSessionConstantsPublicNonVirtuals", 2B147D84-6481-39D6-9E13-DFA306842D56)]
    runtimeclass MultiplayerSessionConstants
    {
        UInt32 MaxMembersInSession { get; set; };
        MultiplayerSessionVisibility MultiplayerSessionVisibility { get; set; };
        Windows.Foundation.Collections.IVectorView<String> InitiatorXboxUserIds { get; };
        String CustomConstantsJson { get; };
        Windows.Foundation.TimeSpan MemberReservationTimeout { get; };
        Windows.Foundation.TimeSpan MemberInactiveTimeout { get; };
        Windows.Foundation.TimeSpan MemberReadyTimeout { get; };
        Windows.Foundation.TimeSpan SessionEmptyTimeout { get; };
        Windows.Foundation.TimeSpan ArbitrationTimeout { get; };
        Windows.Foundation.TimeSpan ForfeitTimeout { get; };
        Boolean CapabilitiesConnectivity { get; };
        Boolean CapabilitiesSuppressPresenceActivityCheck { get; };
        Boolean CapabilitiesGameplay { get; };
        Boolean CapabilitiesLarge { get; };
        Boolean CapabilitiesConnectionRequiredForActiveMember { get; };
        Boolean CapabilitiesCrossplay { get; };
        Boolean CapabilitiesUserAuthorizationStyle { get; };
        Boolean CapabilitiesTeam { get; };
        Boolean CapabilitiesSearchable { get; };
        Boolean CapabilitiesArbitration { get; };
        Boolean EnableMetricsLatency { get; };
        Boolean EnableMetricsBandwidthDown { get; };
        Boolean EnableMetricsBandwidthUp { get; };
        Boolean EnableMetricsCustom { get; };
        MultiplayerManagedInitialization ManagedInitialization { get; };
        MultiplayerMemberInitialization MemberInitialization { get; };
        MultiplayerPeerToPeerRequirements PeerToPeerRequirements { get; };
        MultiplayerPeerToHostRequirements PeerToHostRequirements { get; };
        String MeasurementServerAddressesJson { get; };
    }

    [interface_name("__IMultiplayerSessionMatchmakingServerPublicNonVirtuals", 845BA528-399D-3ACC-94EE-2E9373060213)]
    runtimeclass MultiplayerSessionMatchmakingServer
    {
        MatchmakingStatus Status { get; };
        String StatusDetails { get; };
        Windows.Foundation.TimeSpan TypicalWait { get; };
        MultiplayerSessionReference TargetSessionRef { get; };
    }

    [interface_name("__IMultiplayerSessionMemberPublicNonVirtuals", E96A2AC6-40FF-3A82-B623-0672FF8ECA82)]
    runtimeclass MultiplayerSessionMember
    {
        UInt32 MemberId { get; };
        String TeamId { get; };
        String XboxUserId { get; };
        String MemberCustomConstantsJson { get; };
        String SecureDeviceAddressBase64 { get; };
        Windows.Foundation.Collections.IMap<String, String> Roles { get; };
        String MemberCustomPropertiesJson { get; };
        String Gamertag { get; };
        MultiplayerSessionMemberStatus Status { get; };
        Boolean IsTurnAvailable { get; };
        Boolean IsCurrentUser { get; };
        Boolean InitializeRequested { get; };
        String MatchmakingResultServerMeasurementsJson { get; };
        String MemberServerMeasurementsJson { get; };
        Windows.Foundation.Collections.IVectorView<MultiplayerSessionMember> MembersInGroup { get; };
        Windows.Foundation.Collections.IVectorView<MultiplayerQualityOfServiceMeasurements> MemberMeasurements { get; };
        String DeviceToken { get; };
        NetworkAddressTranslationSetting Nat { get; };
        UInt32 ActiveTitleId { get; };
        UInt32 InitializationEpisode { get; };
        Windows.Foundation.DateTime JoinTime { get; };
        MultiplayerMeasurementFailure InitializationFailureCause { get; };
        MultiplayerSessionReference TournamentTeamSessionRef { get; };
        Windows.Foundation.Collections.IVectorView<String> Groups { get; set; };
        Windows.Foundation.Collections.IVectorView<String> Encounters { get; set; };
        Windows.Foundation.Collections.IMap<String, TournamentTeamResult> Results { get; };
        TournamentArbitrationStatus ArbitrationStatus { get; };
    }

    [interface_name("__IMultiplayerSessionPropertiesPublicNonVirtuals", 07C42B10-B64C-3F8B-A2EA-E753986EB873)]
    runtimeclass MultiplayerSessionProperties
    {
        Windows.Foundation.Collections.IVectorView<String> Keywords { get; set; };
        MultiplayerSessionRestriction JoinRestriction { get; set; };
        MultiplayerSessionRestriction ReadRestriction { get; set; };
        Windows.Foundation.Collections.IVectorView<MultiplayerSessionMember> TurnCollection { get; set; };
        String MatchmakingTargetSessionConstantsJson { get; };
        String SessionCustomPropertiesJson { get; };
        String MatchmakingServerConnectionString { get; };
        Windows.Foundation.Collections.IVectorView<String> ServerConnectionStringCandidates { get; };
        Windows.Foundation.Collections.IVectorView<UInt32> SessionOwnerIndices { get; };
        String HostDeviceToken { get; };
        Boolean Closed { get; };
        Boolean Locked { get; };
        Boolean AllocateCloudCompute { get; };
    }

    [interface_name("__IMultiplayerSessionReferencePublicNonVirtuals", EAD9A671-00FD-3C63-BB68-468341B557B9)]
    [static_name("__IMultiplayerSessionReferenceStatics", 6AE857BB-E109-35ED-8301-D03357F5FEB2)]
    runtimeclass MultiplayerSessionReference
    {
        MultiplayerSessionReference();
        [constructor_name("__IMultiplayerSessionReferenceFactory", 2E34C2E3-BE7D-3E11-A46F-32AD47F80203)]
        {
            MultiplayerSessionReference(String serviceConfigurationId, String sessionTemplateName, String sessionName);
        }
        static MultiplayerSessionReference ParseFromUriPath(String uriPath);
        String ServiceConfigurationId { get; };
        String SessionTemplateName { get; };
        String SessionName { get; };
        String ToUriPath();
    }

    [interface_name("__IMultiplayerSessionRoleTypesPublicNonVirtuals", 077288FF-C313-3296-A411-5453F017FF5E)]
    runtimeclass MultiplayerSessionRoleTypes
    {
        Windows.Foundation.Collections.IMap<String, MultiplayerRoleType> RoleTypes { get; };
    }

    [interface_name("__IMultiplayerSessionStatesPublicNonVirtuals", 3916AB2F-F227-32C8-8ABA-DF162634B9F1)]
    runtimeclass MultiplayerSessionStates
    {
        Windows.Foundation.DateTime StartTime { get; };
        MultiplayerSessionReference SessionReference { get; };
        MultiplayerSessionStatus Status { get; };
        MultiplayerSessionVisibility Visibility { get; };
        Boolean IsMyTurn { get; };
        String XboxUserId { get; };
        UInt32 AcceptedMemberCount { get; };
        MultiplayerSessionRestriction JoinRestriction { get; };
        Windows.Foundation.Collections.IVectorView<String> Keywords { get; };
    }

    [interface_name("__IMultiplayerSessionTournamentsServerPublicNonVirtuals", A0FEF537-85BD-31FA-8745-3F2FA97E0D01)]
    runtimeclass MultiplayerSessionTournamentsServer
    {
        TournamentReference TournamentReference { get; };
        Windows.Foundation.Collections.IMap<String, MultiplayerSessionReference> Teams { get; };
        TournamentRegistrationState RegistrationState { get; };
        TournamentRegistrationReason RegistrationReason { get; };
        Windows.Foundation.DateTime NextGameStartTime { get; };
        MultiplayerSessionReference NextGameSessionRef { get; };
        Windows.Foundation.DateTime LastGameEndTime { get; };
        TournamentTeamResult LastTeamResult { get; };
        TournamentGameResultSource LastGameResultSource { get; };
    }

    [interface_name("__IMultiplayerSubscriptionLostEventArgsPublicNonVirtuals", FCA4B007-0C12-3444-9A79-B1646E2193FD)]
    runtimeclass MultiplayerSubscriptionLostEventArgs
    {
    }

    [interface_name("__IWriteSessionResultPublicNonVirtuals", 76F5FEB8-EC29-36FA-A901-B61C10C90D1D)]
    runtimeclass WriteSessionResult
    {
        Boolean Succeeded { get; };
        MultiplayerSession Session { get; };
        WriteSessionStatus Status { get; };
    }
}