namespace Microsoft.Xbox.Services.GameServerPlatform
{
    enum GameServerFulfillmentState
    {
        Unknown,
        Fulfilled,
        Queued,
        Aborted,
    };

    enum GameServerHostStatus
    {
        Unknown,
        Active,
        Queued,
        Aborted,
        Error,
    };

    [interface_name("__IAllocationResultPublicNonVirtuals", 3E22C098-732E-3939-9994-F14BB1B84340)]
    runtimeclass AllocationResult
    {
        GameServerFulfillmentState FulfillmentState { get; };
        String HostName { get; };
        String SessionHostId { get; };
        String Region { get; };
        Windows.Foundation.Collections.IVectorView<GameServerPortMapping> PortMappings { get; };
        String SecureDeviceAddress { get; };
    }

    [interface_name("__IClusterResultPublicNonVirtuals", 280460DE-C1B9-399E-BDA8-3128857F98B9)]
    runtimeclass ClusterResult
    {
        Windows.Foundation.TimeSpan PollInterval { get; };
        GameServerFulfillmentState FulfillmentState { get; };
        String HostName { get; };
        String Region { get; };
        Windows.Foundation.Collections.IVectorView<GameServerPortMapping> PortMappings { get; };
        String SecureDeviceAddress { get; };
    }

    [interface_name("__IGameServerImageSetPublicNonVirtuals", C4710FEB-8F0F-3CB3-A453-CCF2936F3267)]
    runtimeclass GameServerImageSet
    {
        UInt64 MinPlayers { get; };
        UInt64 MaxPlayers { get; };
        String Id { get; };
        String Name { get; };
        UInt64 SelectionOrder { get; };
        String SchemaContent { get; };
        String SchemaName { get; };
        String SchemaId { get; };
        Windows.Foundation.Collections.IMap<String, String> Tags { get; };
    }

    [interface_name("__IGameServerMetadataResultPublicNonVirtuals", 95DCFF81-C19B-3CAE-9E7B-D97AFF1BEBB0)]
    runtimeclass GameServerMetadataResult
    {
        Windows.Foundation.Collections.IVectorView<GameVariant> GameVariants { get; };
        Windows.Foundation.Collections.IVectorView<GameServerImageSet> GameServerImageSets { get; };
    }

    [interface_name("__IGameServerPlatformServicePublicNonVirtuals", 1A690220-0FC1-3C16-8EB6-0041CD88E182)]
    runtimeclass GameServerPlatformService
    {
        Windows.Foundation.IAsyncOperation<ClusterResult> AllocateClusterAsync(
            UInt32 gameServerTitleId,
            String serviceConfigurationId,
            String sessionTemplateName,
            String sessionName,
            Boolean abortIfQueued);
        Windows.Foundation.IAsyncOperation<ClusterResult> AllocateClusterInlineAsync(
            UInt32 gameServerTitleId,
            String serviceConfigurationId,
            String sandboxId,
            String ticketId,
            String gsiSetId,
            String gameVariantId,
            UInt64 maxAllowedPlayers,
            String location,
            Boolean abortIfQueued);
        Windows.Foundation.IAsyncOperation<GameServerTicketStatus> GetTicketStatusAsync(
            UInt32 gameServerTitleId,
            String ticketId);
        [method_name("GetGameServerMetadataAsync2")] 
        Windows.Foundation.IAsyncOperation<GameServerMetadataResult> GetGameServerMetadataAsync(
            UInt32 titleId,
            UInt32 maxAllowedPlayers,
            Boolean publisherOnly,
            UInt32 maxVariants,
            String locale);
        [method_name("GetGameServerMetadataAsync1")] 
        Windows.Foundation.IAsyncOperation<GameServerMetadataResult> GetGameServerMetadataAsync(
            UInt32 titleId,
            UInt32 maxAllowedPlayers,
            Boolean publisherOnly,
            UInt32 maxVariants,
            String locale,
            Windows.Foundation.Collections.IMap<String, String> filterTags);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<QualityOfServiceServer> > GetQualityOfServiceServersAsync();
        Windows.Foundation.IAsyncOperation<AllocationResult> AllocateSessionHost(
            UInt32 gameServerTitleId,
            Windows.Foundation.Collections.IVectorView<String> locations,
            String sessionId,
            String cloudGameId,
            String gameModeId,
            String sessionCookie);
        Windows.Foundation.IAsyncOperation<AllocationResult> GetSessionHostAllocationStatus(
            UInt32 gameServerTitleId,
            String sessionId);
    }

    [interface_name("__IGameServerPortMappingPublicNonVirtuals", 3E1555B2-A11A-3897-83EE-B91BD866DE94)]
    runtimeclass GameServerPortMapping
    {
        String PortName { get; };
        UInt32 InternalPortNumber { get; };
        UInt32 ExternalPortNumber { get; };
    }

    [interface_name("__IEventsServicePublicNonVirtuals", F8386A41-3F9B-3BDD-BA30-B80B72DCA633)]
    runtimeclass GameServerTicketStatus
    {
        String TicketId { get; };
        String ClusterId { get; };
        UInt32 TitleId { get; };
        String HostName { get; };
        GameServerHostStatus Status { get; };
        String Description { get; };
        String SecureContext { get; };
        Windows.Foundation.Collections.IVectorView<GameServerPortMapping> PortMappings { get; };
        String GameHostId { get; };
        String Region { get; };
    }

    [interface_name("__IGameVariantPublicNonVirtuals", 17D6E9E9-C8B3-3C00-98DF-84ED485AEC6D)]
    runtimeclass GameVariant
    {
        String Id { get; };
        String Name { get; };
        Boolean IsPublisher { get; };
        UInt64 Rank { get; };
        String SchemaContent { get; };
        String SchemaName { get; };
        String SchemaId { get; };
    }

    [interface_name("__IQualityOfServiceServerPublicNonVirtuals", 1A5DD7A9-49E7-3167-BFC2-4DEC58720467)]
    runtimeclass QualityOfServiceServer
    {
        String ServerFullQualifiedDomainName { get; };
        String SecureDeviceAddressBase64 { get; };
        String TargetLocation { get; };
    }
}