namespace Microsoft.Xbox.Services.RealTimeActivity
{
    enum RealTimeActivityConnectionState
    {
        Connected,
        Connecting,
        Disconnected,
    };

    enum RealTimeActivitySubscriptionError
    {
        NoError = 0,
        JsonError = 1008,
        RTAGenericError = 1500,
        RTASubscriptionLimit = 1501,
        RTAAccessDenied = 1502,
    };

    enum RealTimeActivitySubscriptionState
    {
        Unknown,
        PendingSubscribe,
        Subscribed,
        PendingUnsubscribe,
        Closed,
    };

    [interface_name("__IRealTimeActivityResyncEventArgsPublicNonVirtuals", 46492D0B-E429-3C13-ABEC-6493A85EA343)]
    runtimeclass RealTimeActivityResyncEventArgs
    {
        String Gamertag { get; };
        String XboxUserId { get; };
        Double Percentile { get; };
        UInt32 Rank { get; };
        Windows.Foundation.Collections.IVectorView<String> Values { get; };
    }

    [interface_name("__IRealTimeActivityServicePublicNonVirtuals", 1B9BEC82-4BAD-3DBA-B002-C69FC9686174)]
    runtimeclass RealTimeActivityService
    {
        [interface_name("__IRealTimeActivityServiceProtectedNonVirtuals", 86FD7014-3A93-35C7-83AA-C37CF27978C9)]
        {
        }
        void Activate();
        void Deactivate();
        event Windows.Foundation.EventHandler<RealTimeActivityConnectionState> RealTimeActivityConnectionStateChange;
        event Windows.Foundation.EventHandler<RealTimeActivitySubscriptionErrorEventArgs> RealTimeActivitySubscriptionError;
        event Windows.Foundation.EventHandler<RealTimeActivityResyncEventArgs> RealTimeActivityResync;
    }

    [interface_name("__IRealTimeActivitySubscriptionErrorEventArgsPublicNonVirtuals", F7FAB77A-53B9-35F2-9DA8-0BB5AF796D17)]
    runtimeclass RealTimeActivitySubscriptionErrorEventArgs
    {
        RealTimeActivitySubscriptionState State { get; };
        UInt32 SubscriptionId { get; };
        String ResourceUri { get; };
        RealTimeActivitySubscriptionError SubscriptionError { get; };
        String ErrorMessage { get; };
    }
}