import "Microsoft.Xbox.Services.Multiplayer.idl";
import "Microsoft.Xbox.Services.RealTimeActivity.idl";

namespace Microsoft.Xbox.Services.Social
{
    enum ReputationFeedbackType
    {
        FairPlayKillsTeammates,
        FairPlayCheater,
        FairPlayTampering,
        FairPlayQuitter,
        FairPlayKicked,
        CommunicationsInappropriateVideo,
        CommunicationsAbusiveVoice,
        InappropriateUserGeneratedContent,
        PositiveSkilledPlayer,
        PositiveHelpfulPlayer,
        PositiveHighQualityUserGeneratedContent,
        CommsPhishing,
        CommsPictureMessage,
        CommsSpam,
        CommsTextMessage,
        CommsVoiceMessage,
        FairPlayConsoleBanRequest,
        FairPlayIdler,
        FairPlayUserBanRequest,
        UserContentGamerpic,
        UserContentPersonalinfo,
        FairPlayUnsporting,
        FairPlayLeaderboardCheater,
    };

    enum SocialNotificationType
    {
        Unknown,
        added,
        changed,
        removed,
    };

    enum SocialRelationship
    {
        All,
        Favorite,
        LegacyXboxLiveFriends,
    };

    [interface_name("__IProfileServicePublicNonVirtuals", 43F2D8DD-83BC-3B27-BBA7-04FFA6EF4800)]
    runtimeclass ProfileService
    {
        Windows.Foundation.IAsyncOperation<XboxUserProfile> GetUserProfileAsync(String xboxUserId);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<XboxUserProfile> > GetUserProfilesAsync(
            Windows.Foundation.Collections.IVectorView<String> xboxUserIds);
        Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<XboxUserProfile> > GetUserProfilesForSocialGroupAsync(
            String socialGroup);
    }

    [interface_name("__IReputationFeedbackItemPublicNonVirtuals", A209CD1F-2DBF-3376-8ABB-6D76ABE7DFCB)]
    runtimeclass ReputationFeedbackItem
    {
        ReputationFeedbackItem();
        [constructor_name("__IReputationFeedbackItemFactory", 57DDD407-A882-38B6-AF9F-881F861858B0)]
        {
            ReputationFeedbackItem(String xboxUserId, ReputationFeedbackType reputationFeedbackType, Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference sessionReference,
                String reasonMessage, String evidenceResourceId);
        }
        String XboxUserId { get; };
        ReputationFeedbackType FeedbackType { get; };
        Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionReference SessionReference { get; };
        String ReasonMessage { get; };
        String EvidenceResourceId { get; };
    }

    [interface_name("__IReputationServicePublicNonVirtuals", 0A7EC1CD-24D8-3F5C-AF9A-AE73A8A3BFC2)]
    runtimeclass ReputationService
    {
        Windows.Foundation.IAsyncAction SubmitReputationFeedbackAsync(
            String xboxUserId,
            ReputationFeedbackType reputationFeedbackType,
            String sessionName,
            String reasonMessage,
            String evidenceResourceId);
        Windows.Foundation.IAsyncAction SubmitBatchReputationFeedbackAsync(
            Windows.Foundation.Collections.IVectorView<ReputationFeedbackItem> feedbackItems);
    }

    [interface_name("__ISocialGroupConstantsPublicNonVirtuals", B57FC7C0-A206-3383-B240-BD2B43F077C3)]
    [static_name("__ISocialGroupConstantsStatics", 06074A85-F160-3730-9DF9-8AAF2F373C35)]
    runtimeclass SocialGroupConstants
    {
        static String Favorite { get; };
        static String People { get; };
    }

    [interface_name("__ISocialRelationshipChangeEventArgsPublicNonVirtuals", 96000542-B10A-3AC1-A612-0A8D53756D76)]
    runtimeclass SocialRelationshipChangeEventArgs
    {
        String CallerXboxUserId { get; };
        SocialNotificationType SocialNotification { get; };
        Windows.Foundation.Collections.IVectorView<String> XboxUserIds { get; };
    }

    [interface_name("__ISocialRelationshipChangeSubscriptionPublicNonVirtuals", 88BCCBEE-5557-342E-8FC6-848AA4A54056)]
    runtimeclass SocialRelationshipChangeSubscription
    {
        Microsoft.Xbox.Services.RealTimeActivity.RealTimeActivitySubscriptionState State { get; };
        String ResourceUri { get; };
        UInt32 SubscriptionId { get; };
        String XboxUserId { get; };
    }

    [interface_name("__ISocialServicePublicNonVirtuals", 56D32F97-E29B-3B4B-9889-7F597EFE7F49)]
    runtimeclass SocialService
    {
        [interface_name("__ISocialServiceProtectedNonVirtuals", 3E28F7FD-EB92-31E7-90F2-F9BDD7A77393)]
        {
        }
        event Windows.Foundation.EventHandler<SocialRelationshipChangeEventArgs> SocialRelationshipChanged;
        [method_name("GetSocialRelationshipsAsync4")]
        Windows.Foundation.IAsyncOperation<XboxSocialRelationshipResult> GetSocialRelationshipsAsync();
        [method_name("GetSocialRelationshipsAsync3")]
        [default_overload]
        Windows.Foundation.IAsyncOperation<XboxSocialRelationshipResult> GetSocialRelationshipsAsync(
            SocialRelationship socialRelationshipFilter);
        [method_name("GetSocialRelationshipsAsync2")]
        Windows.Foundation.IAsyncOperation<XboxSocialRelationshipResult> GetSocialRelationshipsAsync(String xboxUserId);
        [method_name("GetSocialRelationshipsAsync1")]
        Windows.Foundation.IAsyncOperation<XboxSocialRelationshipResult> GetSocialRelationshipsAsync(
            SocialRelationship socialRelationshipFilter,
            UInt32 startIndex,
            UInt32 maxItems);
        SocialRelationshipChangeSubscription SubscribeToSocialRelationshipChange(String xboxUserId);
        void UnsubscribeFromSocialRelationshipChange(SocialRelationshipChangeSubscription subscription);
    }

    [interface_name("__IXboxSocialRelationshipPublicNonVirtuals", D7E4826D-245D-3706-8AD0-6DFDD60D4B8C)]
    runtimeclass XboxSocialRelationship
    {
        String XboxUserId { get; };
        Boolean IsFavorite { get; };
        Boolean IsFollowingCaller { get; };
        Windows.Foundation.Collections.IVectorView<String> SocialNetworks { get; };
    }

    [interface_name("__IXboxSocialRelationshipResultPublicNonVirtuals", FB9F8D2E-19DA-3787-B097-017C600CD316)]
    runtimeclass XboxSocialRelationshipResult
    {
        Windows.Foundation.Collections.IVectorView<XboxSocialRelationship> Items { get; };
        UInt32 TotalCount { get; };
        Boolean HasNext { get; };
        Windows.Foundation.IAsyncOperation<XboxSocialRelationshipResult> GetNextAsync(UInt32 maxItems);
    }

    [interface_name("__IXboxUserProfilePublicNonVirtuals", 73ED5ABC-39EF-3D76-ADA4-95DF8325FDBB)]
    runtimeclass XboxUserProfile
    {
        String ApplicationDisplayName { get; };
        Windows.Foundation.Uri ApplicationDisplayPictureResizeUri { get; };
        String GameDisplayName { get; };
        Windows.Foundation.Uri GameDisplayPictureResizeUri { get; };
        String Gamerscore { get; };
        String Gamertag { get; };
        String XboxUserId { get; };
    }
}