//All GUIDs came from "EmbeddedXvd/Windows/System32/config/SOFTWARE" and "appmodel.dll".
namespace Windows.Xbox.Services
{
	[interface_name("IXboxLiveConfiguration", fdeeeb27-66b0-465b-9dfb-99c62a62f7bc)]
    	[static_name("IXboxLiveConfigurationStatics", af86e2e0-b12d-4c6a-9c5a-d7aa65101e90)]
	runtimeclass XboxLiveConfiguration
	{
		String TitleId { get; };
		String PrimaryServiceConfigId { get; };
		String SandboxId { get; };
	};
};