#include "Windows.Xbox.Speech.Recognition.SpeechRecognizer.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Speech::Recognition::implementation
{
    void SpeechRecognizer::Close()
    {

    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognitionResult> SpeechRecognizer::RecognizeAsync()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncAction SpeechRecognizer::PreloadGrammarsAsync()
    {
        co_return;
    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSettings SpeechRecognizer::Settings()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechGrammarSet SpeechRecognizer::Grammars()
    {
        throw hresult_not_implemented();
    }
    void SpeechRecognizer::StartContinuousRecognition()
    {

    }
    void SpeechRecognizer::StopContinuousRecognition()
    {

    }
    void SpeechRecognizer::ResumeContinuousRecognition()
    {

    }
    bool SpeechRecognizer::PauseOnContinuousRecognitionResultAvailable()
    {
        return true;
    }
    void SpeechRecognizer::PauseOnContinuousRecognitionResultAvailable(bool value)
    {

    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerInformation SpeechRecognizer::GetRecognizer()
    {
        throw hresult_not_implemented();
    }
    void SpeechRecognizer::SetRecognizer(winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerInformation const& recognizerInformation)
    {

    }
    winrt::event_token SpeechRecognizer::AudioProblemOccurred(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechAudioProblemOccurredEventArgs> const& audioProblemOccuredHandler)
    {
        return {};
    }
    void SpeechRecognizer::AudioProblemOccurred(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::AudioCaptureStateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerAudioCaptureStateChangedEventArgs> const& audioCaptureStateChangedHandler)
    {
        return {};
    }
    void SpeechRecognizer::AudioCaptureStateChanged(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::ContinuousRecognitionResultAvailable(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::ContinuousSpeechRecognitionResultEventArgs> const& continuousRecognitionResultAvailableHandler)
    {
        return {};
    }
    void SpeechRecognizer::ContinuousRecognitionResultAvailable(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::ContinuousRecognitionStatusChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::ContinuousSpeechRecognitionStatusEventArgs> const& continuousRecognitionStatusChangedHandler)
    {
        return {};
    }
    void SpeechRecognizer::ContinuousRecognitionStatusChanged(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::HypothesisAvailable(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechHypothesisResultEventArgs> const& hypothesisAvailableHandler)
    {
        return {};
    }
    void SpeechRecognizer::HypothesisAvailable(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::SoundStarted(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSoundStartedEventArgs> const& soundStartedHandler)
    {
        return {};
    }
    void SpeechRecognizer::SoundStarted(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::SoundEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSoundEndedEventArgs> const& soundEndedHandler)
    {
        return {};
    }
    void SpeechRecognizer::SoundEnded(winrt::event_token const& cookie) noexcept
    {

    }
    winrt::event_token SpeechRecognizer::PhraseStarted(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerPhraseStartedEventArgs> const& phraseStartedHandler)
    {
        return {};
    }
    void SpeechRecognizer::PhraseStarted(winrt::event_token const& cookie) noexcept
    {

    }
}
